# Generated by Django 3.0.4 on 2020-03-29 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100)),
                ('soyadi', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('yazi', models.TextField()),
                ('zaman', models.DateTimeField(default=django.utils.timezone.now)),
                ('degerlendirme', models.CharField(choices=[('5', 'Çok İyi'), ('4', 'İyi'), ('3', 'Kararsızım'), ('2', 'Kötü'), ('1', 'Çok Kötü')], max_length=10)),
            ],
        ),
    ]
