# Generated by Django 3.0.4 on 2020-03-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0002_auto_20200329_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='iletisimmodel',
            name='goruldu',
            field=models.BooleanField(default=False),
        ),
    ]
