# Generated by Django 3.0.4 on 2020-04-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('yazi', models.TextField()),
                ('tip', models.CharField(choices=[('1', 'Düz Yazı'), ('2', 'Günlük')], max_length=10)),
                ('yayim_tarihi', models.DateTimeField(blank=True, null=True)),
                ('kayit_tarihi', models.DateTimeField(default=True)),
            ],
        ),
    ]
